

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/common-lime-butterfly-smoothie-3d-078da6e1f86c4d2ca874e3f4381becb8
Title: Common Lime Butterfly (Smoothie-3D)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from "@react-spring/three";
import butterfly from "../assets/3d/common_lime_butterfly_smoothie-3d.glb";

const Animated_butterfly = (props) => {
  const { nodes, materials } = useGLTF(butterfly)
  return (
    <a.group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Textured}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </a.group>
  )
}

useGLTF.preload(butterfly)

export default Animated_butterfly